CREATE TABLE IF NOT EXISTS User (
  id SERIAL PRIMARY KEY,
  created DATE NOT NULL DEFAULT DATE(NOW),
  role VARCHAR(255) NOT NULL CHECK (role in ('admin', 'user')),
  firstname VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  passwordHash VARCHAR(255) NOT NULL,
);

CREATE TABLE IF NOT EXISTS Item (
  id SERIAL PRIMARY KEY,
  created DATE NOT NULL,
  content VARCHAR(1023) NOT NULL,
  owner INTEGER REFERENCES User,
);

CREATE TABLE IF NOT EXISTS ItemUser (
  item_id INTEGER REFERENCES Item(id) ON DELETE CASCADE,  
  user_id INTEGER REFERENCES User(id) ON DELETE CASCADE,
);

TIMESTAMP?